name: dump

on:
  workflow_run:
    workflows: [preflight]
    branches: [master, main]
    types:
      - completed

jobs:
  job1:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v2
      - uses: ahmadnassri/action-workflow-run-wait@v1

      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Dump job context
        env:
          JOB_CONTEXT: ${{ toJSON(job) }}
        run: echo "$JOB_CONTEXT"
      - name: Dump steps context
        env:
          STEPS_CONTEXT: ${{ toJSON(steps) }}
        run: echo "$STEPS_CONTEXT"
      - name: Dump runner context
        env:
          RUNNER_CONTEXT: ${{ toJSON(runner) }}
        run: echo "$RUNNER_CONTEXT"
      - name: Dump strategy context
        env:
          STRATEGY_CONTEXT: ${{ toJSON(strategy) }}
        run: echo "$STRATEGY_CONTEXT"
      - name: Dump matrix context
        env:
          MATRIX_CONTEXT: ${{ toJSON(matrix) }}
        run: echo "$MATRIX_CONTEXT"

      - uses: technote-space/get-diff-action@v4
        id: git-diff
        with:
          PATTERNS: |
            **/*.sh
          FILES: |
            hello.sh
            yarn.lock
            .eslintrc

      - name: show-diff
        env:
          GIT_DIFF: ${{ toJSON(steps.git-diff) }}
        run: |
          echo "${GIT_DIFF}"

      - name: diff
        if: steps.git-diff.outputs.diff
        run: |
          echo "Some shell scripts are modified."
